In [71]:
from sklearn.datasets import load_iris
from pymfe.mfe import MFE
import numpy as np
import pandas as pd

data = load_iris()
y = data.target
X = data.data

# indices = np.random.randint(low=100, high=len(X), size=35)
# X = np.delete(X, indices, axis=0)
# y = np.delete(y, indices, axis=0)

# Extract general, statistical and information-theoretic measures
mfe = MFE(groups=["Complexity"])
mfe.fit(X, y)
ft = mfe.extract()

# # Extract all available measures
# mfe = MFE(groups="all")
# mfe.fit(X, y)
# ft = mfe.extract()
# print(ft)

In [72]:
ydf = pd.DataFrame(list(y))
ydf.columns
ydf.groupby(0).count()

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [73]:
type(ft)
df = pd.DataFrame(list(ft))

df = df.transpose()
pd.set_option('display.max_rows', df.shape[0]+1)

In [74]:
df

            0           1
0          c1           1
1          c2           0
2    cls_coef    0.902951
3     density     0.84877
4     f1.mean    0.277564
5       f1.sd    0.261262
6    f1v.mean   0.0267996
7      f1v.sd   0.0337704
8     f2.mean  0.00638177
9       f2.sd   0.0110535
10    f3.mean    0.123333
11      f3.sd     0.21362
12    f4.mean   0.0433333
13      f4.sd   0.0750555
14  hubs.mean    0.955078
15    hubs.sd   0.0684096
16    l1.mean  0.00432559
17      l1.sd  0.00749215
18    l2.mean   0.0133333
19      l2.sd    0.023094
20    l3.mean  0.00666667
21      l3.sd    0.011547
22        lsc    0.817911
23         n1         0.1
24    n2.mean    0.212068
25      n2.sd    0.135143
26    n3.mean   0.0466667
27      n3.sd    0.211631
28    n4.mean  0.00666667
29      n4.sd   0.0816497
30    t1.mean    0.015625
31      t1.sd   0.0251477
32         t2   0.0266667
33         t3   0.0133333
34         t4         0.5