In [164]:
from scipy.io import arff
import pandas as pd
import os

In [165]:
def fetch_datasets(dataset):
    
    data = arff.loadarff('../datasets/luis/' + dataset)
    metadata = data[1]
    data = pd.DataFrame(data[0])
    
    instances = len(data)
    classes = len(data.iloc[:,-1].value_counts())
    attributes = len(data.columns)- 1
    nominal_attributes = str(metadata).count("nominal")
    
    proportion = data.iloc[:,-1].value_counts()
    proportion = proportion.map(lambda x: round(x/instances*100,2))

    majority = max(proportion)
    minority = min(proportion)

    
    return {
        "name": dataset[:-5],
        "instances": instances,
        "classes": classes,
        "attributes": attributes,
        "nominal attributes": nominal_attributes,
        "majority": majority,
        "minority": minority
    }

In [166]:
datasets = os.listdir('../datasets/luis')

In [167]:
data = []

for ds in datasets:
    data.append(fetch_datasets(ds))

data = pd.DataFrame.from_dict(data)

In [168]:
data

,name,instances,classes,attributes,nominal attributes,majority,minority
0,21_car,1728,4,6,7,70.02,3.76
1,40474_thyroid-allbp,2800,5,26,21,58.29,1.11
2,1501_semeion,1593,10,256,1,10.17,9.73
3,1121_badges2,294,2,10,4,71.43,28.57
4,1528_volcanoes-a2,1623,5,3,1,90.63,1.79
...,...,...,...,...,...,...,...
136,30_page-blocks,5473,5,10,1,89.77,0.51
137,1480_ilpd,583,2,10,2,71.36,28.64
138,46_splice,3190,3,60,61,51.88,24.04
139,1556_acute-inflammations,120,2,6,6,50.83,49.17
140,450_analcatdata_lawsuit,264,2,4,2,92.80,7.20